Fix/Change placeholder and text colors to match design system
AdaloHQ/react-multi-menu pull request #17
Opened 2021-11-16 21:16 UTC by danicunhac

Changed some colors to match our design system, all of them described by Nataliia.

2021-11-16 21:17 UTC, danicunhac commented
![](https://github.trello.services/images/mini-trello-icon.png) [Can delete all filters appropriately](https://trello.com/c/Fi0vffN0/17-can-delete-all-filters-appropriately)

2021-12-01 17:09 UTC, paulopompeu approved these changes

2021-12-01 19:23 UTC, vkkostin requested changes
I think you also need to compile the css with `yarn compile:css`. That should update the `./styles.css` file with your changes.

2021-12-01 19:56 UTC, danicunhac commented
> I think you also need to compile the css with `yarn compile:css`. That should update the `./styles.css` file with your changes.

That's right. I ended up removing the changed file when testing.

2021-12-01 19:59 UTC, vkkostin approved these changes

2021-12-09 18:32 UTC, merged